import org.apache.hadoop.ipc.proto.GenericRefreshProtocolProtos.GenericRefreshResponseCollectionProtoOrBuilder;
public class FunctionUse2034 {
public void funcUse() {
GenericRefreshResponseCollectionProtoOrBuilder genericrefreshresponsecollectionprotoorbuilder = new GenericRefreshResponseCollectionProtoOrBuilder();
genericrefreshresponsecollectionprotoorbuilder.getResponsesOrBuilder(null);
}
}