import org.apache.hadoop.security.proto.RefreshAuthorizationPolicyProtocolProtos.RefreshAuthorizationPolicyProtocolService;
public class FunctionUse10687 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolService refreshauthorizationpolicyprotocolservice = new RefreshAuthorizationPolicyProtocolService();
refreshauthorizationpolicyprotocolservice.newBlockingStub(null);
}
}